### ISSUE TITLE
20241127 Todo-List

### ISSUE THREAD

**Issue by Anxi77** [Meta8ThTeamCodingGuzi/Project_Realms#12]
화이팅

**Comment by Jine99** [comment]
나는 스킬 만들어야지

**Comment by hyeonji9178** [comment]
1.맵 빵꾸  보수하고 꾸며야함(벽세우기랑 쪼매 꾸밈)
2.무기랑 다른 아이템 아이콘들 싹 골라서 구워놓고 
3.인벤에셋에 담겨있는 스트립트 뜯어보기 (장착 시스템 만들어야함)

**Comment by Jine99** [comment]
TODO 24.11.27 화염방사 만들거임 기록

**Comment by hyeonji9178** [comment]
20241128
아이콘도 오늘 다 구워(갑옷은 했고,무기랑...)
스킬 아이콘  골라
맵 증축 할거임
인벤 UI

**Comment by Anxi77** [comment]
1. BoolStat GetstatValue  캐스팅 오류 디버그
2. 새로 구현한 스킬들(Area , Point ...) 변수이름 , 클래스명 수정
3. Skill Slot UI 구현해야합니다.

**Comment by Anxi77** [comment]
수고하셨습니다
