### ISSUE TITLE
20241128 ToDo List

### ISSUE THREAD

**Issue by Anxi77** [Meta8ThTeamCodingGuzi/Project_Realms#18]
오늘도 활기차게 시작입니다 ^^

@Jine99  @hyeonji9178

**Comment by Anxi77** [comment]
1. BoolStat GetstatValue 캐스팅 오류 디버그
2. 새로 구현한 스킬들(Area , Point ...) 변수이름 , 클래스명 수정
3. Skill Slot UI 구현해야합니다

**Comment by hyeonji9178** [comment]
1.아이콘도 오늘 다 구워야함.
2.인벤스킬슬롯 UI 만들기
3.맵 증축 할거임

**Comment by Jine99** [comment]
1.버프 디버프 구현
2.몬스터 애니메이션 초안 설계
