### ISSUE TITLE
20241129 Todo-List

### ISSUE THREAD

**Issue by Anxi77** [Meta8ThTeamCodingGuzi/Project_Realms#24]
화이팅이에옹 에옹

**Comment by Jine99** [comment]
1.몬스터 애니메이션 전부 구현 및 FSM 수정
2.플레이어 FSM 구현 및 애니메이션 구현

(다이어울프 작업시작)

**Comment by hyeonji9178** [comment]
1.UI 수정(버튼달기,QWER버튼처럼 보이는 UI달기)
2.맵 만들기(중앙맵 구성)
![r고사리](https://github.com/user-attachments/assets/1fdc9001-741e-4448-97e9-2afb52daa3d7)

**Comment by Anxi77** [comment]
0.저녁준비
1.스킬 시스템 (기본 공격도 스킬 변경 하겠읍니다)  및 디버그 (스탯 초기화 문제)
2.아이템 시스템 확인 
3. 자장가 확인
