### ISSUE TITLE
20241202 TODO

### ISSUE THREAD

**Issue by Anxi77** [Meta8ThTeamCodingGuzi/Project_Realms#35]
## 최현성

몹 아이템 드롭 기능 구현
투사체 스킬 약간 메롱인거 확인

https://github.com/Meta8ThTeamCodingGuzi/Project_Realms/blob/46550282d3827f2f1eea749bc520cb2a1ed41e9b/Realm/Assets/Main/Scripts/Unit/Monster/Monster.cs#L169-L174

몬스터 스폰할 떄 널참조 오류 ㅜㅜ

https://github.com/Meta8ThTeamCodingGuzi/Project_Realms/blob/ea87faf86493cc0dd756414faecb20be8c1722c6/Realm/Assets/Main/Scripts/UI/Player/Item/Slot.cs#L57-L88

이거 실장착 하여 렌더러 업데이트 하는것도 리그 완성되면 ㄱㄱ

**Comment by hyeonji9178** [comment]
1.오늘 맵 전부 완성시키고,나중에 수정할거생기면업뎃 ㄱㄱ
2.툴팁창 ui맹글기 (마우스 가져다대면 어떤건지 설명이 나오게만들것)
3.스킬 찍는창(모든 스킬이 있고 스크롤도가능 )
