### ISSUE TITLE
20241204 TODO List

### ISSUE THREAD

**Issue by Anxi77** [Meta8ThTeamCodingGuzi/Project_Realms#42]
## 최현성

플레이어 어택에서 택댐(애니메이션 끝날때까지 못넘어가게끔 해야할듯)
플레이어 원거리 기본공격 정상화
스킬 찍는 UI랑 스킬매니저랑 연동
아이템 툴팁 , 스킬 툴팁 구현

## 김진

몬스터스테이트 끝내고 , 보스몹 패턴 구현 ,몬스터 (평타도 스킬로(tryuseskill 호출하게끔)) / (원거리 에너미 하나 만들어야함)

## 김현지

펫 플레이어 졸졸 따라다니다가 에너미가 펫의 감지 범위 안에 들어오게 되면 에너미를 추적하게끔

**Comment by Jine99** [comment]
하잇!

**Comment by hyeonji9178** [comment]
와카리마시타~
